// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzOjmc4Ih8L7PoPfX8AuYaF2AEtU6Yw7w',
    appId: '1:976720855178:ios:2be76b440d235d9ac5ed73',
    messagingSenderId: '976720855178',
    projectId: 'pc-12311',
    databaseURL: 'https://pc-12311-default-rtdb.firebaseio.com',
    storageBucket: 'pc-12311.firebasestorage.app',
    iosBundleId: 'com.example.pcbuilder',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe_56sGhFX7R5z3-HQVIeWb8BN3Gs2dOY',
    appId: '1:976720855178:web:6966b1614fb3efbec5ed73',
    messagingSenderId: '976720855178',
    projectId: 'pc-12311',
    authDomain: 'pc-12311.firebaseapp.com',
    databaseURL: 'https://pc-12311-default-rtdb.firebaseio.com',
    storageBucket: 'pc-12311.firebasestorage.app',
    measurementId: 'G-L14DSR7GH8',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzOjmc4Ih8L7PoPfX8AuYaF2AEtU6Yw7w',
    appId: '1:976720855178:ios:2be76b440d235d9ac5ed73',
    messagingSenderId: '976720855178',
    projectId: 'pc-12311',
    databaseURL: 'https://pc-12311-default-rtdb.firebaseio.com',
    storageBucket: 'pc-12311.firebasestorage.app',
    iosBundleId: 'com.example.pcbuilder',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiGzFx0HOVx9oyNDIdMg9S2CxFBRFC3JQ',
    appId: '1:976720855178:android:e834eef8e4c6e048c5ed73',
    messagingSenderId: '976720855178',
    projectId: 'pc-12311',
    databaseURL: 'https://pc-12311-default-rtdb.firebaseio.com',
    storageBucket: 'pc-12311.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe_56sGhFX7R5z3-HQVIeWb8BN3Gs2dOY',
    appId: '1:976720855178:web:e82b82b315fe55b8c5ed73',
    messagingSenderId: '976720855178',
    projectId: 'pc-12311',
    authDomain: 'pc-12311.firebaseapp.com',
    databaseURL: 'https://pc-12311-default-rtdb.firebaseio.com',
    storageBucket: 'pc-12311.firebasestorage.app',
    measurementId: 'G-DS22G1ZVK4',
  );

}